=== ehabarman/novels-core/src/main/resources/configurations/filters.xml.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <xsd:element name="filters">
      <xsd:complexType mixed="true">
         <xsd:sequence>
            <xsd:element name="provider"/>
            <xsd:element name="pre">
               <xsd:complexType>
                  <xsd:sequence>
                     <xsd:element name="filter" minOccurs="0" maxOccurs="1000">
                        <xsd:complexType mixed="true">
                           <xsd:sequence >
                              <xsd:element name="name" type="xsd:string"/>
                              <xsd:element name="class" type="xsd:string"/>
                              <xsd:element name="order" type="xsd:integer"/>
                           </xsd:sequence>
                        </xsd:complexType>
                     </xsd:element>
                  </xsd:sequence>
               </xsd:complexType>
            </xsd:element>
            <xsd:element name="post">
               <xsd:complexType>
                  <xsd:sequence>
                     <xsd:element name="filter" minOccurs="0" maxOccurs="1000">
                        <xsd:complexType>
                           <xsd:sequence>
                              <xsd:element name="class" type="xsd:string"/>
                              <xsd:element name="name" type="xsd:string"/>
                              <xsd:element name="order" type="xsd:integer"/>
                           </xsd:sequence>
                        </xsd:complexType>
                     </xsd:element>
                  </xsd:sequence>
               </xsd:complexType>
            </xsd:element>
         </xsd:sequence>
      </xsd:complexType>
   </xsd:element>
</xsd:schema>

=== ehabarman/novels-core/src/main/resources/configurations/filters.xml
<?xml version="1.0" encoding="utf-8" ?>
<filters xsi:noNamespaceSchemaLocation="filters.xml.xsd"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <provider>FiltersConfig</provider>
   <pre>
      <filter>
         <name>extractUserDetailsFilter</name>
         <class>com.itsmite.novels.core.filters.pre.ExtractUserDetailsFilter</class>
         <order>1</order>
      </filter>
      <filter>
         <name>requestLoggingFilter</name>
         <class>com.itsmite.novels.core.filters.pre.RequestLoggingFilter</class>
         <order>2</order>
      </filter>
   </pre>

   <post>
   </post>
</filters>
